source "https://rubygems.org"

ruby "3.3.4"

gem "rails", "~> 7.1.4"
gem "bcrypt", "~> 3.1"
gem "bootstrap-sass", "~> 3.4"
gem "sassc-rails", "~> 2.1"
gem "sprockets-rails"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "puma", ">= 5.0"
gem "bootsnap", require: false
gem "pg", "~> 1.1"
gem "rubocop", "~> 1.66", require: false
gem "faker", "~> 3.5"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
end

group :development do
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem "rails-controller-testing", "~> 1.0"
  gem "minitest", "~> 5.25"
  gem "minitest-reporters", "~> 1.7"
  gem "guard", "~> 2.18"
  gem "guard-minitest", "~> 2.4"
end

